INSERT INTO `menu_items` VALUES 
(1, 101,'Chicken Nuggets', 'Hot and Crispy Nuggets with some added spices', 5.6),
(2, 101, 'Vegetable Spring Roll', 'Roll consisting of mixed vegetables with crispy wonton wrapper', 8.7),
(3, 106, 'Chocolate Lava Cake', 'Lava Cake consisting of Hot Chocolate', 6.8),
(4, 101, 'French Fries', 'Hot and Crispy French Fries with Ranch', 3.6),
(5, 102, 'Chicken Soup', 'Hot Liquid Soup with Tinge of Chicken and Spices', 7.05),
(6, 104, 'Veggie Delight', 'A mix of boiled veggies with cheese and salad', 8.4),
(7, 103, 'Garden Salad', 'Fresh Romaine Lettuce with added carrots and grape tomatoes', 10.2),
(8, 106, 'Chocolate Brownie', 'Brownie with dry fruits topping', 6.8),
(9, 105, 'Orange Chicken', 'Chicken dipped in Orange Sauce', 6.7),
(10, 106,'Steak Burger', 'Burger consisting of Steak and Sauce', 12.6),
(11, 101, 'Beef Spring Roll', 'Roll consisting of beef with crispy wonton wrapper',  105),
(12, 103, 'Romaine Salad', 'Fresh Romaine Lettuce with added cheese', 8.2),
(13, 106, 'Flavoured Yoghurt', 'Yoghurt in different flavours', 4.8),
(14, 102, 'Chicken Pizza', 'Hot and Soft Pizza with olives and chicken', 10.05),
(15, 104, 'Veg Sub', 'A mix of boiled veggies with salad dressing', 7.6),
(16, 102, 'Chicken Burger', 'Burger consisting of Chicken and Cheese', 7.05),
(17, 104, 'Chocolate Cookies', 'Choco Chip Cookies baked in low flame', 4.4),
(18, 103, 'SoftDrink', 'Drinks with Ice Cubes', 3.2);
